name: "slack-notify"
description: send notification via SlackAPI

inputs:
  color:
    description: Color
    default: primary # primary, danger
    required: true
  status:
    description: Deployment Status
    default: x # x = failed, tada = successful, warning = warning
    required: true

runs:
  using: "composite"
  steps:
    - name: Post to a Slack channel
      id: slack-json
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}
      with:
        channel-id: ${{ inputs.CHANNEL_ID }}
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Sam deploy status: :${{inputs.status}}:",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "This is a mrkdwn section block :ghost: *this is bold*, and ~this is crossed out~, and <https://google.com|this is a link>"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "style": "${{inputs.color}}",
                    "text": {
                      "type": "plain_text",
                      "text": "Commit :twisted_rightwards_arrows:",
                      "emoji": true
                    },
                    "value": "commit",
                    "action_id": "github-commit",
                    "url": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  },
                  {
                    "type": "button",
                    "style": "${{inputs.color}}",
                    "text": {
                      "type": "plain_text",
                      "text": "Action :link:",
                      "emoji": true
                    },
                    "value": "action",
                    "action_id": "github-action",
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }
