name: slack-notify

on:
  push:
    branches:
      - main

jobs:
  send-slack:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        run: |
          echo "::set-output name=BRANCH_NAME::${GITHUB_REF#refs/heads/}"
        shell: bash

      - name: Set COMMIT_MESSAGE
        run: |
          echo ::set-output name=COMMIT_MESSAGE::$(echo "${{ github.event.head_commit.message }}" | tr '\n' ' ')
        shell: bash

      - name: Send slack
        uses: ./.github/actions/slack
        with:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          color: 00FF00
          status: tada
