name: test-slacks

on:
  push:
    branches:
      - main

jobs:
  send-slack:
    runs-on: ubuntu-22.04

    # strategy:
    #   matrix:
    #     python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - id: set_var
        run: |
          content=`cat ${PWD}/.github/templates/slack.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=slackJson::$content"

      - name: Post to a Slack channel (In-line)
        id: slack-in-line
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: ${{ secrets.CHANNEL_ID }}
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Post to a Slack channel (JSON)
        id: slack-json
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{ secrets.CHANNEL_ID }}
          # For posting a rich message using Block Kit
          payload: $PAYLOAD
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          PAYLOAD: ${{fromJson(steps.set_var.outputs.slackJson).payload}}
