name: test-slacks

on:
  push:
    branches:
      - main

jobs:
  send-slack:
    runs-on: ubuntu-22.04

    # strategy:
    #   matrix:
    #     python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        run: |
          echo "::set-output name=BRANCH_NAME::${GITHUB_REF#refs/heads/}"
        shell: bash

      - name: Set COMMIT_MESSAGE
        run: |
          echo ::set-output name=COMMIT_MESSAGE::$(echo "${{ github.event.head_commit.message }}" | tr '\n' ' ')
        shell: bash

      - name: Post to a Slack channel (In-line)
        id: slack-in-line
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: ${{ secrets.CHANNEL_ID }}
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Post to a Slack channel (JSON)
        id: slack-json
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{ secrets.CHANNEL_ID }}
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Sam deploy status:  :tada: :white_check_mark: :warning:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "This is a mrkdwn section block :ghost: *this is bold*, and ~this is crossed out~, and <https://google.com|this is a link>"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "style": "danger",
                      "text": {
                        "type": "plain_text",
                        "text": "Commit :twisted_rightwards_arrows:",
                        "emoji": true
                      },
                      "value": "commit",
                      "action_id": "github-commit",
                      "url": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    },
                    {
                      "type": "button",
                      "style": "primary",
                      "text": {
                        "type": "plain_text",
                        "text": "Action :link:",
                        "emoji": true
                      },
                      "value": "action",
                      "action_id": "github-action",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
